apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-service
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    name: http
  - port: 80
    targetPort: 80
    nodePort: 30001
