apiVersion: v1
kind: Pod
metadata:
  name: nginxpod-1
  labels:
    name: nginxpod-1
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      requests: 
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
