apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    name: nodeapp
spec:
  containers:
  - name: nodeapp-container
    image: vijayvct/nodeapp
    ports:
      - containerPort: 3000
